### ISSUE TITLE
🐞 Having Loop running may interfere with movable rect from builtin screenshot tool

### ISSUE THREAD

**Issue by luckman212** [MrKai77/Loop#480] opened 2024-06-28 18:48 UTC
### Bug Description

> pulled over from https://github.com/MrKai77/Loop/issues/459#issuecomment-2189390099

When using the <kbd>⌘cmd</kbd>+<kbd>⇧shift</kbd>+<kbd>4</kbd> keyboard shortcut to take screenshots, previously I could hold and release the spacebar while the <kbd>⌃CTRL</kbd> key was being held down to move the capture rectangle around. Now this only works 10-20% of the time, other times pressing spacebar does nothing. I never had this happen before, so I am fairly sure it's related somehow.

It is not 100% reproducible. I will try to come up with 100% repro steps.

I'm running appver 1.1.0 (1120) now.

### Steps To Reproduce

1. Start an interactive rect screenshot using <kbd>⌘cmd</kbd>+<kbd>⇧shift</kbd>+<kbd>4</kbd>
2. Draw a rect on the screen, but do not release the mouse button (yet)
3. Press and hold <kbd>[SPACEBAR]</kbd> to move rect
4. Sometimes, it doesn't work.

### MacOS Version

14.5

### Loop Version

Version 🧪 1.1.0 (1120)

**Comment by luckman212** [comment] 2024-06-28 18:51
Here are my keybinds in case it's relevant

<img width="1172" alt="image" src="https://github.com/MrKai77/Loop/assets/1992842/1dbe4d63-6e81-426e-acf5-a9799547adfd">

<img width="1172" alt="image" src="https://github.com/MrKai77/Loop/assets/1992842/4b35e54c-986c-4ed3-b9cf-1ef74d26c246">

**Comment by MrKai77** [comment] 2024-07-10 00:15
Hey @luckman212, I am unable to reproduce this bug on my side, even when replicating your setup. Can you try other trigger keys and see if the bug persists there? Additionally, I would recommend trying the latest prerelease.

**Comment by luckman212** [comment] 2024-07-10 00:18
Thanks @MrKai77 

I switched to the "dev" builds last week, so I am always on the latest prerelease now.

I haven't noticed this happening as much or maybe at all in the last few days, so I'll pay close attention again. And I will try changing my triggers to not include the CTRL key.

**Comment by MrKai77** [comment] 2024-07-18 08:28
Alright, I will be closing this as solved for now, but please feel free to reopen this if you re-encounter this bug!

**Closed as completed by MrKai77** 2024-07-18 08:28 UTC
Labels: Bug

**Comment by luckman212** [comment] 2024-07-18 11:23
No problem - I haven't reproduced the bug with the recent dev builds. Running very solid!
