### ISSUE TITLE
🐛 Loop doesn't work properly when 'Animate windows being resized' is enabled

### ISSUE THREAD

**Issue by andrwmai** [MrKai77/Loop#355] opened 2024-05-14 17:48 UTC
### Bug Description

I use 2 screens, an external screen and the MacBook Pro's built-in screen. When 'Animate windows being resized' is enabled, I can't Loop within the built-in screen. If I Loop, it puts the window in my external screen (set as main display), and not even in the correct position.

I'm attaching a screen recording of this issue shown in my built-in screen. The first part of the recording shows the issue, and the rest shows the expected behavior when the feature is disabled.

### Steps To Reproduce

1. Enable 'Animate windows being resized'
2. Try Looping in one of the screens, I'm assuming it happens to the one that's not set as the main display
3. Watch it being resized/positioned in the main display instead and not the screen you want

### Expected Behavior

Normal resizing/positioning like when the feature is disabled.

### Actual Behavior

It puts the window in the wrong screen.

### Screenshots

https://github.com/MrKai77/Loop/assets/48293860/30f9cc1d-c5ee-457c-87c0-ae2f3c756f40

### MacOS Version

Sonoma 14.5

### Loop Version

1.0.0-beta.15

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment] 2024-05-14 22:09
That's really weird.. and just to make sure, you can't reproduce this bug when the macbook's screen is set to the main display right?

**Comment by andrwmai** [comment] 2024-05-15 07:52
Yes, that's correct. If the built-in display is the main display then everything works totally fine. The gif below shows my external display and where the window goes to when looping in the built-in display with the feature enabled.

![CleanShot 2024-05-15 at 2  50 23](https://github.com/MrKai77/Loop/assets/48293860/c4f619ca-977a-4530-ae58-4d2ecedbbcb4)

**Comment by MrKai77** [comment] 2024-05-16 03:18
Alright, that is a very weird bug. I will look into it!

**Comment by andrwmai** [comment] 2024-05-22 09:11
Checking in to see if there's been any progress. :) And lmk if you need any testing I'm happy to help.

**Comment by MrKai77** [comment] 2024-05-22 23:20
Yep, I've actually nearly done reworking window animations as a whole :D
I have posted a build here: https://github.com/MrKai77/Loop/issues/298#issuecomment-2125925937
Maybe that will already fix this issue?

**Comment by andrwmai** [comment] 2024-05-23 06:54
Just tested it and indeed it's fixed the issue of the window being moved to my external screen. However, the behavior isn't the same. Before when I selected a window in my external screen, and with my cursor in my MacBook screen, the window moved to my MacBook screen when I looped, now it only moves to the screen where it's at even when my cursor is on another screen. I think the previous behavior is more convenient in some circumstances.

**Comment by PKizzle** [comment] 2024-05-23 12:42
Maybe let users decide which behavior they prefer using a setting?

**Comment by MrKai77** [comment] 2024-05-23 17:24
Yes, that is currently being tracked on #251, where I am planning to make it configurable :)

**Comment by andrwmai** [comment] 2024-05-23 17:34
Yes! Is there a development build that we can test? :)

Also, I'm super excited for the new UI update!

**Comment by MrKai77** [comment] 2024-05-24 02:59
Not yet.. it's still missing a few things :)
But you can follow its development on #361!

**Comment by MrKai77** [comment] 2024-05-24 03:00
I'll also be closing this issue since it seems to have been fixed!

**Closed as completed by MrKai77** 2024-05-24 03:00 UTC
Labels: Bug
