### ISSUE TITLE
✨ hide Icon on top bar

### ISSUE THREAD

**Issue by baschte** [MrKai77/Loop#135] opened 2023-12-25 09:33 UTC
### Feature Request Description

Hey @MrKai77 i would love to see if you can add a setting to hide the App Icon on top. I think it doesnt have to be there the whole time. Possible Solution could be that you have to Open Loop again to see the settings window if its hidden in the top bar.

what do you think?

best regards 

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by JaceThings** [comment] 2023-12-25 14:14
I do "like" the idea of hiding the menu bar icon. Some would argue for accessibility, but I 100% agree with "opening settings when I launch Loop if it's already open."

**Comment by baschte** [comment] 2023-12-25 16:45
Hey @Soft-Bred i agree for accessibility reasons. Thats why i would leave the Option disabled by default to prevent issues here.

**Comment by MrKai77** [comment] 2023-12-25 19:22
Duplicate of #78.
I'll probably implement it so that the menubar icon is visible by default, and that if it's toggled off, the settings window is shown once the app is opened again. I'll probably include this in the description of the toggle button to make that less confusing as well.

**Closed as completed by MrKai77** 2023-12-25 19:22 UTC
Labels: Feature
