### ISSUE TITLE
✨ Customized Roulette Wheel

### ISSUE THREAD

**Issue by ohhcarina** [MrKai77/Loop#271] opened 2024-03-28 02:10 UTC
### Feature Request Description

I hope the wheel can be customized! For example, moving the cursor to the right side of the wheel means 3/4 of the screen on the right, but it just right half now. The default settings are not frequently used by me. 

That's the feature I most desire! 

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment] 2024-03-28 02:46
Duplicate of #107

**Closed as not planned by MrKai77** 2024-03-28 02:46 UTC
Labels: Feature
