### ISSUE TITLE
✨ Add the option to disable the radial menu if only the shortcuts are used

### ISSUE THREAD

**Issue by Sborzov456** [MrKai77/Loop#220] opened 2024-02-17 20:36 UTC
### Feature Request Description

If I want to use only the keyboard, I would like to be able to disable the appearance of the radial menu.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment] 2024-02-18 00:51
I believe that this is a duplicate of #183. It is in the build posted [here](https://github.com/MrKai77/Loop/issues/183#issuecomment-1915927547) :)

**Closed as completed by MrKai77** 2024-02-18 00:51 UTC
Labels: Feature

**Comment by Sborzov456** [comment] 2024-02-18 10:50
Yes, this is what i need! Will this feature be in the main build?
