### ISSUE TITLE
✨ Keybinds to make window larger or smaller

### ISSUE THREAD

**Issue by lighterless** [MrKai77/Loop#228] opened 2024-02-24 16:02 UTC
### Feature Request Description

It would be nice to get keybinds to make the window larger or smaller. This feature exists in Raycast and it's the only thing keeping me from fully switching to Loop.

### Screenshots

![raycast_make_bigger](https://github.com/MrKai77/Loop/assets/41703801/5e34e759-0ebf-484c-b341-a5a75a2685f1)
![raycast_make_smaller](https://github.com/MrKai77/Loop/assets/41703801/d6c982a1-ba0a-436b-8dea-d0b4d6d0f6ff)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment] 2024-02-25 01:45
Duplicate of #155. Unfortunately, I'm super busy this week so I probably won't be able to get it done yet. But this issue is quite high on my priority list, so it will definitely be implemented soon :)

**Closed as completed by MrKai77** 2024-02-25 01:45 UTC
Labels: Feature
