### ISSUE TITLE
✨is there a way to hide the circle icon when i move the windows?

### ISSUE THREAD

**Issue by justincnn** [MrKai77/Loop#274] opened 2024-03-28 08:16 UTC
### Feature Request Description

![](https://i.imgur.com/7FIasbi.png)

is there a way to hide the circle icon when i move the windows?

### Screenshots

![](https://i.imgur.com/7FIasbi.png)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by JaceThings** [comment] 2024-03-28 14:27
make your delay 100s 
![006969@2x](https://github.com/MrKai77/Loop/assets/60551230/b3a194a2-71a5-4d85-9df5-656f7268f3a1)

**Comment by MrKai77** [comment] 2024-03-28 17:37
Thanks @Soft-Bred! Yup, this is a duplicate of #183. However, since this seems to be a popular request, I think I will just add a toggle button haha (plus who wants a delay on the radial menu itself anyway??)

**Closed as completed by MrKai77** 2024-03-28 17:37 UTC
Labels: Feature

**Comment by justincnn** [comment] 2024-03-29 02:26
> Thanks @Soft-Bred! Yup, this is a duplicate of #183. However, since this seems to be a popular request, I think I will just add a toggle button haha (plus who wants a delay on the radial menu itself anyway??)

thanks for your attention !
anyway ,i cannot find the setting of Delay:

![](https://i.imgur.com/U3mFzU2.png)

**Comment by JaceThings** [comment] 2024-03-29 02:31
Make sure to use the build linked here.

https://github.com/MrKai77/Loop/issues/183#issuecomment-2025885175

**Comment by justincnn** [comment] 2024-03-29 03:12
> Make sure to use the build linked here.
> 
> [#183 (comment)](https://github.com/MrKai77/Loop/issues/183#issuecomment-2025885175)

thanks for your quickly advice:)


all the Keybindings is unworkable,when i installed the version you mentioned(https://github.com/MrKai77/Loop/issues/183#issuecomment-2025885175).

any solution?tks again.

**Comment by MrKai77** [comment] 2024-03-29 03:19
Please try this build: https://github.com/MrKai77/Loop/issues/155#issuecomment-2026550185
It is slightly newer, so maybe that might fix it? Otherwise, I am unable to reproduce that bug.

**Comment by justincnn** [comment] 2024-03-29 03:45
> Please try this build: [#155 (comment)](https://github.com/MrKai77/Loop/issues/155#issuecomment-2026550185) It is slightly newer, so maybe that might fix it? Otherwise, I am unable to reproduce that bug.

amazing work,so many tks
