### ISSUE TITLE
🐛 Loop settings page keeps pop up without triggering

### ISSUE THREAD

**Issue by yclau97** [MrKai77/Loop#210] opened 2024-02-11 07:07 UTC
### Bug Description

Will keep pop up loop settings right after accessing Mac system settings.

### Steps To Reproduce

1. Access Mac system settings
2. Close Mac system settings
3. Loop settings page will instantly pop up without triggering it

### Expected Behavior

Loop settings page will not pop up.

### Actual Behavior

Loop settings page will pop up without triggering it after accessing Mac system settings.

### MacOS Version

Sonoma 14.3

### Loop Version

Version 1.0.0-beta.14 (644)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment] 2024-02-13 00:25
Thanks for the report! This seems to be a duplicate of #197, so I'll be closing this :)

**Closed as completed by MrKai77** 2024-02-13 00:25 UTC
Labels: Bug
