### ISSUE TITLE
✨ Keyboard shortcut to increase/decrease  size of a window

### ISSUE THREAD

**Issue by Dhairy2003** [MrKai77/Loop#224] opened 2024-02-19 06:31 UTC
### Feature Request Description

A feature to instantly increase or decrease window size using keyboard shortcuts . Have attached a video to showcase how it should work 

### Screenshots

https://github.com/MrKai77/Loop/assets/101127874/6ee964ba-0e42-4ba6-9e02-18af1a7f14f6

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment] 2024-02-19 18:07
Duplicate of #155, but I am planning to finish this really soon!

**Closed as completed by MrKai77** 2024-02-19 18:07 UTC
Labels: Feature
