### ISSUE TITLE
🐞 Center switch not working

### ISSUE THREAD

**Issue by lucifercr07** [MrKai77/Loop#416] opened 2024-06-19 06:51 UTC
### Bug Description

When trying to switch to Center via `fn + <any key>` it maximizes to full screen

### Steps To Reproduce

1. Set key binding to `fn + <any key>` for Center
2. Try to switch it'll maximise the window to full screen
![image](https://github.com/MrKai77/Loop/assets/13472823/bf14f4fe-49b6-4876-8aad-f5ed47b27f67)

### Expected Behavior

Should switch window to center

### Actual Behavior

Maximises the window to full screen

### MacOS Version

Sonoma 14.5

### Loop Version

1.0.0 (1030)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment] 2024-06-19 07:09
I am unable to reproduce this on my side. Can you export your keybinds from the "Advanced" tab, and send it here? I will take a look.

**Comment by MrKai77** [comment] 2024-06-27 00:51
@lucifercr07 any updates on this?

**Comment by lucifercr07** [comment] 2024-06-27 04:01
@MrKai77 it happens with me when there's external monitor connected. I'd try to do a screen recording and share when time permits.

**Comment by MrKai77** [comment] 2024-07-03 03:34
I believe that the latest prerelease will fix this. Please reopen this issue if not, but I will be closing this for now.

**Closed as completed by MrKai77** 2024-07-03 03:34 UTC
Labels: Bug
