### ISSUE TITLE
🐛 Window animations don't work when preview is disabled

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#147] opened 2024-01-02 15:51 UTC
### Bug Description

Windows do not animate when the "Show Preview when looping" setting is disabled and the "Animate windows being resized" setting is on

### Steps To Reproduce

1. Turn off Preview
2. Turn on Window Animations
3. Move a window
4. Watch as the window doesn't animate

### Expected Behavior

1. Turn off Preview
2. Turn On Window Animations
3. Window should animate instantly 

### Actual Behavior

1. Turn off Preview
2. Turn on Window Animations
3. Move a window
4. Watch as the window doesn't animate

### Screenshots

https://github.com/MrKai77/Loop/assets/60551230/40d62b06-4301-4aaa-9154-675d0bc29ef0

### MacOS Version

14.2.1 (23C71)

### Loop Version

Version 1.0.0-beta.13 (599)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment] 2024-01-03 20:59
The reason for this is that when the current action on the radial menu is changed when the window is already animating itself, it tries to run both window animations, leading to a super glitchy experience.

To try and fix this, I have tried making a notification system to stop the current window animation asynchronously before the next one, but that ended up still being super laggy, and it also somehow (badly) interfered with other apps on my mac 😅

So at the moment, this issue is unfixable, but I have been planning to make an entirely new window animation system that should work more reliably with all apps, at which point I may be able to fix this issue :)

**Comment by JaceThings** [comment] 2024-01-03 21:07
Great to hear (the last part, not the... the failing part). Can't wait!

I hope it gets smoother soon too! Notion, in particular, has a peculiar property that makes the animation super smooth, while other apps don't.

Uploading 002390.mp4…

**Comment by MrKai77** [comment] 2024-05-17 21:07
Oh, I just realized that this is basically just #298!
Since I have already posted some progress there, I will instead be closing this as the duplicate of that :)

**Closed as not planned by MrKai77** 2024-05-17 21:07 UTC
Labels: Bug
