### ISSUE TITLE
✨ Customize the radial menu's operations

### ISSUE THREAD

**Issue by biscuitbicky** [MrKai77/Loop#311] opened 2024-04-02 09:22 UTC
### Feature Request Description

When using Loop, I rarely make a window occupy the top half or the bottom half of the whole screen. However, it's much more frequent to maximize or minimize a window. Although it's available to maximize a window by move the cursor outward inside the radial menu (and it works pretty well), but I would prefer it can work this way: 
* when the cursor is moving upward outside the radial menu (picture 1), the window selected will maximize to fill the whole screen. 
* when the cursor is moving downward outside the radial menu (picture 2), the window selected will minimize to the dock, just like pressing the shortkey "Cmd + m".

**So, if it's possibile for user to customize the behavior when a corner was selected?**

By the way, I hope the behavior inside the radial menu can be customized too. like, the cursor moving inward is cancel the operation (Just like how user did in the latest release). And, when cursor moving outward, it means center the windows.
Thanks for your patience and contributions so so much! Loop is really a cool software! 
<img width="1738" alt="Xnip2024-04-02_16-13-16" src="https://github.com/MrKai77/Loop/assets/110220931/ab12a57c-7e36-4cc9-8de0-a1c10395a915">
<img width="1738" alt="Xnip2024-04-02_16-13-49" src="https://github.com/MrKai77/Loop/assets/110220931/8e6c7365-e952-46b4-9856-a6fc6be51890">

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment] 2024-04-02 13:43
Thank you so much! This seems like a duplicate of #107, so you can track progress there :)

**Closed as not planned** 2024-04-02 13:43 UTC
Labels: Feature
