### ISSUE TITLE
✨ Allow for dev version

### ISSUE THREAD

**Issue by SenpaiHunters** [MrKai77/Loop#441] opened 2024-06-21 11:54 UTC
### Feature Description:

Allow users to test unstable and/or developmental versions of Loop ahead of its normal release. 

### Why Do You Want This?:

… yes, two modes for users.

**Comment by JaceThings** [comment] 2024-06-21 13:24
duplicate of #182 🤭

**Comment by SenpaiHunters** [comment] 2024-06-21 13:25
Shhh @Soft-Bred it's fine (I was too lazy to find the other one), plus it's a different method 😂

**Closed as completed** 2024-06-26 05:52 UTC
