### ISSUE TITLE
✨ Resize other windows while resizing one of the windows

### ISSUE THREAD

**Issue by StalinCCCP** [MrKai77/Loop#339] opened 2024-04-24 09:08 UTC
### Feature Request Description

Just like what the macOS native windows tiling function does, when there're two(or more) windows controlled by Loop, resizing one of the window will cause other windows to resize automatically.

### Screenshots

https://github.com/MrKai77/Loop/assets/62281472/5c9b4dcd-d231-4afc-83a6-80ec42bb42fc

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment] 2024-04-25 04:08
Seems like a duplicate of #264 :)

**Closed as not planned by MrKai77** 2024-04-25 04:08 UTC
Labels: Feature
