### ISSUE TITLE
🐛 Raycast Can't Use The "Trigger Key"

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#102] opened 2023-11-30 15:12 UTC
### Bug Description

I have a Raycast command that activates via `⌘⌥⌃⇧` `Space`, Loop's "Trigger Key" is also `⌘⌥⌃⇧`. When Loop is open, Raycast does not register `⌘⌥⌃⇧` as a pressed button

### Steps To Reproduce

1. Install Raycast.
2. Go to Extensions.
3. Set a hotkey for any command to ⌘⌥⌃⇧ Space.
4. Try it; it should work.
5. Install Loop.
6. Set the Trigger Key to ⌘⌥⌃⇧.
7. Try to activate the Raycast command using the hotkey; it should fail.

### Expected Behavior

Loop is only activated when the Trigger Key + Secondary Key is pressed.

### Actual Behavior

Loop takes over Raycast's ability to register "Trigger Key".

### Screenshots

https://github.com/MrKai77/Loop/assets/60551230/1c68150b-cd8f-4634-8cb1-fb8c7a638a04

### MacOS Version

14.1.1 (23B81)

### Loop Version

1.0.0-beta.12 (515)

### Additional Context

I feel like this could be solved by making the radial menu a toggle, since I do not even use it with my mouse, and it does not provide additional value when using the keyboard.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment] 2023-11-30 16:20
I believe this is a duplicate of #74 (correct me if I'm wrong)

> I feel like this could be solved by making the radial menu a toggle, since I do not even use it with my mouse, and it does not provide additional value when using the keyboard.

Interesting! I was thinking that I could make it an option to only make the radial menu show when an appropriate keyboard shortcut has been pressed. (As said in #74)

**Comment by JaceThings** [comment] 2023-11-30 16:31
Yep, you are right. I missed this since it's the second ticket from the bottom 😭

**Comment by MrKai77** [comment] 2023-11-30 16:52
No problem! 😉

**Closed as completed by MrKai77** 2023-11-30 16:52 UTC
Labels: Bug
