### ISSUE TITLE
✨ Add a setting to disable Loop in fullscreen mode

### ISSUE THREAD

**Issue by patelheet30** [MrKai77/Loop#488] opened 2024-07-01 19:42 UTC
### Feature Request Description

Essentially, I have an issue when running games. This is mainly focused on games like Cities Skylines, Minecraft etc which have their own game launcher, opening up a new application that isn't readily found in Finder. Minecraft opens a new "java" application that I can't find in Finder and can't add to the Excluded apps list. I use the command keybinding for crouching in Minecraft which also happens to be my Loop keybinding meaning every time I crouch twice by mistake, I end up exiting out of fullscreen mode and then being forced to resize it again. By fullscreen mode, I mean the green button in MacOS's traffic light and not Minecraft's inbuilt Fullscreen mode which is buggy asf.

This would also help with normal games which you can find in Finder. How? Well because most people (sane people, I hope) play games in Fullscreen, so this would also help them as they would not need to manually add each game to the excluded apps list.

I would probably say a toggleable setting would work for this so people can choose if they want Loop to work in Fullscreen or not.

### Screenshots

![Arc at 2024-07-01 at 20 42 09@2x](https://github.com/MrKai77/Loop/assets/75808215/bcecf35d-03ef-4167-83eb-60ae19d0b5d9)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment] 2024-07-03 03:31
Great idea! Sounds like a duplicate of #199, though :)

**Closed as not planned by MrKai77** 2024-07-03 03:31 UTC
Labels: Feature
