### ISSUE TITLE
✨ More sizes for loop

### ISSUE THREAD

**Issue by bduff9** [MrKai77/Loop#325] opened 2024-04-11 15:44 UTC
### Feature Request Description

Would it be possible to turn on additional sizes for the loop based on how far your mouse was from the center?  For instance, I love the half and quarters but also sometimes need thirds.  So if I could turn on thirds and then when I start leaving the loop, maybe it shows ⅔ of the screen, then move a little further and it drops to ½ of the screen, and then even further still it goes to ⅓.  I think this would be super helpful on the horizontal and vertical directions.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment] 2024-04-11 23:42
Thanks!
I believe that this is a duplicate of #108 :)

**Closed as not planned by MrKai77** 2024-04-11 23:42 UTC
Labels: Feature
