### ISSUE TITLE
✨ More preview window customization options

### ISSUE THREAD

**Issue by frieza213** [MrKai77/Loop#114] opened 2023-12-11 16:51 UTC
### Feature Request Description

Make the preview more customizable, as in option to change color, blur etc.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment] 2023-12-12 00:34
Yup! 
Adjustable blur is planned in #103.

**Comment by MrKai77** [comment] 2024-03-26 23:36
Since this is essentially a duplicate of #103, I'll be closing this to prevent any duplication :)

**Closed as not planned by MrKai77** 2024-03-26 23:36 UTC
Labels: Feature
