### ISSUE TITLE
✨ Maximize/Snap windows over the dock

### ISSUE THREAD

**Issue by tombuben** [MrKai77/Loop#428] opened 2024-06-19 20:28 UTC
### Feature Request Description

When used in conjunction with apps like IntelliDock that intelligently hide the dock when it is overlapped by any icon, it would be nice for Loop to have an option that would take this into account and operate with the area that would be taken up by a screen with the dock hidden, even when the dock is currently visible - both for maximizing and for snapping to bottom sides of the screen.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment] 2024-06-19 20:44
Seems like a duplicate of #367 :)

**Closed as not planned by MrKai77** 2024-06-19 20:44 UTC
Labels: Feature
