### ISSUE TITLE
🐛 Previous Screen and Next Screen can't use control button

### ISSUE THREAD

**Issue by Pirate-Pianist** [MrKai77/Loop#354] opened 2024-05-14 15:17 UTC
### Bug Description

![image](https://github.com/MrKai77/Loop/assets/25580279/dccd4acf-f86e-4da9-8b22-2ead0498ffb9)

Function:
Previous Screen, command + opt + left + control, doesn't work;
Next Screen, command + opt + right + control, doesn't work;

### Steps To Reproduce

![image](https://github.com/MrKai77/Loop/assets/25580279/123d3410-ad85-4464-b5bf-92a985cd5f73)

### Expected Behavior

Press command + opt + left + control = Previous Screen
Press command + opt + right + control = Next Screen

### Actual Behavior

Press command + opt + left + control = Left Cycle
Press command + opt + right + control = Right Cycle

### Screenshots

![image](https://github.com/MrKai77/Loop/assets/25580279/190ce47c-37c3-4a1b-9a40-3c34047a2f61)

### MacOS Version

Sonoma 14.4.1 (23E224)

### Loop Version

Version 1.0.0-beta.15 (817)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment] 2024-05-14 22:17
And it works when the normal arrow keys are set to change the screen for the window right? If yes, then I believe that the system is interfering with Loop. Can you check that these settings are disabled:
<img width="782" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/aa749f4c-ff99-4b3c-8249-eb2256768742">
It's located in Settings -> Keyboard -> Keyboard Shortcuts... -> Mission Control -> Mission Control Dropdown.

**Comment by MrKai77** [comment] 2024-05-22 23:33
Alright, I'll be closing this since I'm confident that the above is the solution, and I cannot reproduce this on my computer.

**Closed as not planned by MrKai77** 2024-05-22 23:33 UTC
Labels: Bug
