### ISSUE TITLE
🐞 Custom window size isn't respected/remembered

### ISSUE THREAD

**Issue by Zabriskije** [MrKai77/Loop#386] opened 2024-06-10 08:32 UTC
### Bug Description

When using the Custom option, the window size is not respected/remembered. Happens both with pixels and percentages.

### Steps To Reproduce

- Add a new Custom key bind
- Modify the pixel/percentage values
- Click on the slider again

### Expected Behavior

 The entered values should remain the same.

### Actual Behavior

 The entered values change when clicked again.

### Screenshots

![values](https://github.com/MrKai77/Loop/assets/101254295/b1dd374f-fc62-453c-8760-620726eb666e)

### MacOS Version

Sonoma 14.5 (23F79)

### Loop Version

Version 1.0.0-beta.15 (817)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by SenpaiHunters** [comment] 2024-06-10 13:44
Can you explain this issue(s) more? As what i can see, the issue is not shown, if you're editing the value, of course, it'll change. As currently, it looks like you're manually editing it as when it's clicked back in the same value is hosted there.

**EDIT: This might be an issue (even though i am blind), and if it is, it's fixed in an upcoming build**

**Comment by MrKai77** [comment] 2024-06-11 03:36
Hey @Zabriskije!
Here's a dev build with the new settings window, which does fix this issue :)
[Loop.zip](https://github.com/user-attachments/files/15781824/Loop.zip)

It is *almost* ready for a little update in #297 too!

**Comment by Zabriskije** [comment] 2024-06-11 08:26
> Can you explain this issue(s) more? As what i can see, the issue is not shown, if you're editing the value, of course, it'll change. As currently, it looks like you're manually editing it as when it's clicked back in the same value is hosted there.
> 
> **EDIT: This might be an issue (even though i am blind), and if it is, it's fixed in an upcoming build**

Yeah, I should have cropped down the GIF, it's hard to see here.
If you input – let's say – 950, the value is shown as 960 if you click again.
&nbsp;

> Hey @Zabriskije! Here's a dev build with the new settings window, which does fix this issue :) [Loop.zip](https://github.com/user-attachments/files/15781824/Loop.zip)
> 
> It is _almost_ ready for a little update in #297 too!

Nice! I love the text animation.
I didn't know if this was worth opening an issue since I knew the new settings window was coming, but I'm glad it's all solved.

**Comment by SenpaiHunters** [comment] 2024-06-11 08:51
Thanks for reporting the issue, @Zabriskije as Kai gave you, it should be fixed now! Any more issues, with this new version or previous, you're always free to make an issue!

**Closed as completed** 2024-06-11 20:13 UTC
Labels: Bug
