### ISSUE TITLE
✨ 希望提供多语言支持 Hope to provide multilingual support

### ISSUE THREAD

**Issue by yamazakitouma** [MrKai77/Loop#272] opened 2024-03-28 02:20 UTC
### Feature Request Description

I hope to use AI for translation and provide support for multiple languages, especially Simplified Chinese. This is very important to me. Thank you

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment] 2024-03-28 02:49
Seems like a duplicate of #270 to me (correct me if I am wrong)

**Closed as not planned by MrKai77** 2024-03-28 02:49 UTC
Labels: Feature
