### ISSUE TITLE
✨Chinese Translation

### ISSUE THREAD

**Issue by hongyinull** [MrKai77/Loop#310] opened 2024-04-02 09:15 UTC
### Feature Request Description

Hello! Even though I don't have software translation experience, I am quite familiar with Simplified and Traditional Chinese. I hope I can help translate this free, open-source, and user-friendly app into Chinese to allow more friends to use it❤️

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by fukai7722** [comment] 2024-04-02 12:43
Also need Chinese Translation

**Comment by MrKai77** [comment] 2024-04-02 13:40
Duplicate of #276 :)
There is a build you can download there to get the Chinese localization!

**Closed as not planned by MrKai77** 2024-04-02 13:40 UTC
Labels: Feature
