### ISSUE TITLE
✨ Allow users to define custom areas

### ISSUE THREAD

**Issue by guid-ooo** [MrKai77/Loop#211] opened 2024-02-12 14:22 UTC
### Feature Request Description

I never find myself using the quarter options, however when using the radial menu these are always an option. 

I would like to be able to define my own layout, kind of similar to windows window management :)

### Screenshots

![image](https://github.com/MrKai77/Loop/assets/113428227/f52e83d8-1a76-4c17-9e17-69f350f924da)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment] 2024-02-13 00:27
Awesome! Would this be a duplicate of #107? Or is this about making the same type of menu that appears in Windows (like the screenshot you sent)? Thanks!

**Comment by MrKai77** [comment] 2024-03-19 01:39
Closing due to inactivity

**Closed as completed by MrKai77** 2024-03-19 01:39 UTC
Labels: Feature
