### ISSUE TITLE
🐞 Setting keybindings for Next and Previous Desktop doesn't work

### ISSUE THREAD

**Issue by yougotwill** [MrKai77/Loop#539] opened 2024-08-15 13:49 UTC
### Bug Description

Hi there 👋 Loop is awesome and I've been enjoying it.

I'm trying to bind the Next and Previous Screens to `Ctrl + Alt + Right Arrow` and `Ctrl + Alt + Left Arrow`. I can make the bindings but nothing happens when I use the key combinations. I had to bind them to the Raycast Window Management Extension's Next and Previous Desktop commands respectively which does the same behaviour and I have confirmed that it works.

### Steps To Reproduce

1. Add keyboard shortcut for Ctrl+Alt+Right Arrow to Next Screen
2. Close Loop settings
3. Press `Ctrl + Alt + Right Arrow`
4. Nothing happens

### Expected Behavior

1. Add keyboard shortcut for Ctrl+Alt+Right Arrow to Next Screen
2. Close Loop settings
3. Press `Ctrl + Alt + Right Arrow`
4. Moves focused app window to the next desktop (aka. space)

### Actual Behavior

1. Add keyboard shortcut for Ctrl+Alt+Right Arrow to Next Screen
2. Close Loop settings
3. Press `Ctrl + Alt + Right Arrow`
4. Nothing happens

### macOS Version

macOS 14.6.1 (23G93) 

### Loop Version

Version 1.1.1 (1259)

### Additional Context

My CPU is Intel if that helps.

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [ ] I can help with fixing or developing this issue (tick if you can help).

**Comment by MrKai77** [comment] 2024-09-12 14:32
That is odd, can you please send a screen recording?

**Comment by yougotwill** [comment] 2024-09-26 13:33
Hi @MrKai77 Sorry I was mistaken. I misunderstood that the commands moved windows between desktops. They actually move between different screens and that works perfectly 👍

Can I open a feature request for moving between desktops?

**Comment by MrKai77** [comment] 2024-09-26 23:00
No problem! I will be marking this as a duplicate of #223, in that case :)

**Closed as not planned by MrKai77** 2024-09-26 23:00 UTC
Labels: Bug
