### ISSUE TITLE
✨ Add compatibility with Logi Options+

### ISSUE THREAD

**Issue by andrwmai** [MrKai77/Loop#342] opened 2024-04-29 13:01 UTC
### Feature Request Description

I use an MX Master 3 from Logitech, and they have an app called Logi Options+ that lets me customize the buttons and gestures on the mouse. I've always assigned a button on the mouse to the shortcut 'Ctrl + Opt + C' which is also the shortcut to center a window in Loop. However, when I use the button on the mouse, Loop doesn't recognize the shortcut hence nothing happens. I hope the compatibility could be added to make the experience even better, especially if I can cycle through the shortcuts using just the button on my mouse.

### Screenshots

![CleanShot 2024-04-29 at 8  00 51@2x](https://github.com/MrKai77/Loop/assets/48293860/49516e78-4b2a-4d58-b8a2-0a9b8bf795ba)
![CleanShot 2024-04-29 at 8  01 03@2x](https://github.com/MrKai77/Loop/assets/48293860/64d94152-d8d4-4362-8a49-b79442b74665)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment] 2024-04-30 02:39
Yup, this is caused by the same issue causing #330.
I will close this as a duplicate as that :)

**Closed as not planned by MrKai77** 2024-04-30 02:39 UTC
Labels: Feature
