### ISSUE TITLE
🐞 Menubar icon display bug

### ISSUE THREAD

**Issue by zhanglolo** [MrKai77/Loop#410] opened 2024-06-18 06:58 UTC
### Bug Description

I use some command to resize menubar icon padding, other icon look well, but loop.

### Steps To Reproduce

1.use this command
```bash
defaults -currentHost write -globalDomain NSStatusItemSpacing -int 10  
defaults -currentHost write -globalDomain NSStatusItemSelectionPadding -int 6  
```
2.reboot mac
3.open loop 

### Expected Behavior

The icon should be in the center of the background.

### Actual Behavior

The icon is shifted to the right and is partially covered.

### Screenshots

![bb897ad593d11ba1216496f1e322eb6a](https://github.com/MrKai77/Loop/assets/27875371/d9a90789-4aae-4a7b-ae12-701df6813c82)

![65fb089a8898d4ff4b83bbc17a5c12a6](https://github.com/MrKai77/Loop/assets/27875371/2d1f7a6c-eddb-400f-90ed-4d0ca3e1f752)

### MacOS Version

Sonoma 14.5

### Loop Version

Version 1.0.0

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by Fred-IV** [comment] 2024-06-18 08:11
Loop and Ice do not like each-other.
The menubar icon doesn't show up.

**Comment by MrKai77** [comment] 2024-06-18 18:26
Seems like a duplicate of #351.

**Closed as not planned by MrKai77** 2024-06-18 18:26 UTC
Labels: Bug
