### ISSUE TITLE
🐛 Stop responding when resize unrealizable window 

### ISSUE THREAD

**Issue by sven97** [MrKai77/Loop#295] opened 2024-03-29 21:59 UTC
### Bug Description

This bug can be triggered under a specific situation: With `Resize window under cursor` is `on`. And at least two windows on screen (one normal application window, one not resizable window: like Loop Setting). After using trigger key and mouse to resize the normal window, hover the mouse on the not resizable window, and press trigger key and try to resize (re-position) the not resizable window, the entire Loop application will stop responding and can only restored via kill process and reopen.

### Steps To Reproduce

1. Turn on `Resize window under cursor`
2. Open at least two windows (one normal application window, one not resizable window: like Loop Setting)
3. Using trigger key and mouse to resize the normal window
4. Hover the mouse on the not resizable window
5. Press trigger key and try to resize (re-position) the not resizable window
6. Application stop responding

### Expected Behavior

Success resize (re-position) the not resizable window

### Actual Behavior

Application stop responding

### Screenshots

https://github.com/MrKai77/Loop/assets/23182824/5287c731-2bb0-4e50-950f-e178acdbb013

### MacOS Version

14.4.1

### Loop Version

1.0.0 (644)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment] 2024-03-29 22:19
Thank you so much for the bug report!

Actually, this is caused by #88. Loop is currently not capable of resizing its own windows. Does it work properly when you try it with other apps that cannot resize?

**Comment by sven97** [comment] 2024-03-29 22:48
Thank you for responding and for creating such an elegant windows management tool! I have double-checked, and the "not responding" issue only occurs with Loop's own windows. I am eagerly awaiting a fix in the next release!

**Comment by MrKai77** [comment] 2024-03-29 22:56
Actually, I just released a new version about an hour ago! Go ahead and try it out!

I'll be closing this issue as a duplicate, but this is something I hope to fix very soon!

**Closed as not planned by MrKai77** 2024-03-29 22:56 UTC
Labels: Bug
