### ISSUE TITLE
🐛 radical menu does not work in some cases

### ISSUE THREAD

**Issue by StalinCCCP** [MrKai77/Loop#334] opened 2024-04-19 02:43 UTC
### Bug Description

The radical menu works well in most of the cases. But in some specific scenarios, it doesn't work at all. Clicking the triggering key, it simply just doesn't pop out. The trigger key is set without conflicting with any other apps.

### Steps To Reproduce

Sometimes, connecting to external display will trigger this bug. Sometimes, simply switching desktops will trigger it. Restarting the app could fix this issue but it's really annoying.

### Expected Behavior

The radical menu should appear once the trigger key was clicked.

### Actual Behavior

It doesn't appear.

### Screenshots

(Wait for me to reproduce such bug)

### MacOS Version

[Sonoma 14.1.1]

### Loop Version

[1.0.0-beta.15 (817)]

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment] 2024-04-19 04:15
Seems like a duplicate of #166. Unfortunately,  it is near impossible to fix something where I don't know where the absolute root cause is (nor do I know how to reproduce it), so it may take a while for me to fix :)

**Closed as not planned by MrKai77** 2024-04-19 04:15 UTC
Labels: Bug
