### ISSUE TITLE
🐛 Loop doesn't work

### ISSUE THREAD

**Issue by Jagerx** [MrKai77/Loop#285] opened 2024-03-29 02:43 UTC
### Bug Description

**Great 1.0.0-beta.14 (742)**

1. when Mouse click on the close button, or command + Q to close the app, settings window will definitely appear, not random. trying the version 1.0.0-beta.14 (742) from #197 , It's ok for now.

2. Used to drag the window to the top edge of the screen to maximise the window, but the version 1.0.0-beta.14 in Release can only achieve Top Half, the problem was also solved after trying version 1.0.0-beta.14 (742) from #197 , thanks!

BTW, really great to have "Disable cursor interaction" option in 1.0.0-beta.14 (742).
https://github.com/MrKai77/Loop/files/14625255/Loop.zip

### Steps To Reproduce

**Still Bugs**
3. Sometimes there is no response suddenly and needs to be restarted to work properly, no reason has been found to trigger the issue.

### Expected Behavior

N/A

### Actual Behavior

N/A

### MacOS Version

Chip Apple M2 macOS Sonoma 14.4.1

### Loop Version

version 1.0.0-beta.14 in Release

### Final Checks

- [ ] My issue title is descriptive
- [ ] This is a single bug (multiple bugs should be reported individually)

**Comment by Jagerx** [comment] 2024-03-29 02:49
When there is no response suddenly, restarting the APP will not solve the problem, and the system needs to be restarted. After working for 3 hours this morning, I have restarted twice, which is annoying.

**Comment by MrKai77** [comment] 2024-03-29 02:53
Awesome to hear!
As for the app stopping randomly, do you believe that this could be a duplicate of #166?

**Comment by Jagerx** [comment] 2024-03-29 03:04
> Awesome to hear! As for the app stopping randomly, do you believe that this could be a duplicate of #166?

Yes, I also checked this Issue #166, but I don't intend to install Raycast which I don't use, in addition I also tried selecting "Quit" in the Loop menu and then reopening the app, but again it doesn't work, have no choice but to reboot the system instead!

**Comment by MrKai77** [comment] 2024-03-29 03:09
Got it! Unfortunately, I am unable to reproduce this, but can you try this latest build: [Loop.zip](https://github.com/MrKai77/Loop/files/14794162/Loop.zip)

**Comment by Jagerx** [comment] 2024-03-29 03:50
It just reappeared again, I really didn't want to reboot again, after waiting a few minutes it was surprisingly fine. 

It's a Twitter APP I had previously installed but never opened, I just opened it for the first time and log into my account, but when I tried to maximize the Twitter window, it failed!

The last time it didn't work was when I opened the Bin and the Finder window of Bin didn't work.

Unable to generalize what triggered the bug, but they're triggering too often in my MAC, Haha, sad = =!

**Comment by MrKai77** [comment] 2024-03-29 03:52
Do you have a link to this Twitter app for MacOS? I want to see if I can reproduce it there.

**Comment by Jagerx** [comment] 2024-03-29 04:02
> Do you have a link to this Twitter app for MacOS? I want to see if I can reproduce it there.

https://apps.apple.com/us/app/twitter/id1482454543

MY Keybindings:
<img width="500" alt="image" src="https://github.com/MrKai77/Loop/assets/42521386/ae3198b5-5b04-4b76-b24c-28bcb87563d1">

**Comment by Jagerx** [comment] 2024-03-29 04:18
I think I may have found part of what triggers the bug, I recently reinstalled Sonoma need to install some apps freshly, and just now, after installing Chrome via brew install --cask google-chrome, after logging into my Chrome account and syncing, the Loop fails again!

Hope this could help you to solve this bug, don't know code, have tried, thanks!

**Comment by Jagerx** [comment] 2024-03-29 05:19
> I think I may have found part of what triggers the bug, I recently reinstalled Sonoma need to install some apps freshly, and just now, after installing Chrome via brew install --cask google-chrome, after logging into my Chrome account and syncing, the Loop fails again!
> 
> Hope this could help you to solve this bug, don't know code, have tried, thanks!

No response for BetterZIP window after install BetterZIP via brew install --cask betterzip

**Comment by MrKai77** [comment] 2024-04-20 07:36
Actually, I believe that from the code perspective that this is caused by the exact same issue causing #166, so I will be closing this as a semi-duplicate of that.

**Closed as not planned** 2024-04-20 07:36 UTC
Labels: Bug
