### ISSUE TITLE
🐞middle-click  problem

### ISSUE THREAD

**Issue by Tamajiang** [MrKai77/Loop#448] opened 2024-06-23 01:42 UTC
### Bug Description

I am unable to trigger the middle-click to arrange windows with my Logitech Master 3s. The settings in Logi Options+ are correct, but the function is not working as expected.

### Steps To Reproduce

click middle button，no response

### Expected Behavior

work like before it's OK

### Actual Behavior

middle click does not work 

### MacOS Version

sonoma 14.5

### Loop Version

1.0.0

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment] 2024-06-23 05:35
Does your trigger key work as intended?

**Comment by solid-pixel** [comment] 2024-06-23 10:39
I also have an MX Master 3, and clicking the middle button does nothing.
The trigger key works correctly.

<img width="664" alt="image" src="https://github.com/MrKai77/Loop/assets/18260178/dc0be0b3-bbc6-4fa6-aae8-7ef65ff443b2">


Loop 1.0
MacBook M1 Pro, macOS Sonoma 14.5 (23F79)

**Comment by Tamajiang** [comment] 2024-06-25 08:20
> Does your trigger key work as intended?
yes

**Comment by MrKai77** [comment] 2024-08-21 16:25
Can you reproduce this in the latest release (1.1.0)?

**Comment by solid-pixel** [comment] 2024-08-24 11:45
> Can you reproduce this in the latest release (1.1.0)?

I can't reproduce in 1.1.1, seems to be triggering fine now, thank you!

**Comment by SenpaiHunters** [comment] 2024-08-26 12:59
@Tamajiang , can you replicate this in v1.1.1?

**Comment by MrKai77** [comment] 2024-09-12 14:34
Closing since this seems to be fixed :)

**Closed as completed** 2024-09-12 14:34 UTC
Labels: Bug

**Comment by solid-pixel** [comment] 2025-03-28 10:11
sorry to bump this but the issue came back :( 

The wheel is mapped correctly to "Middle button" in Logi Options +, and the Middle-click toggle in Loop's settings is set to `on`.

The Trigger Key works correctly.

![Image](https://github.com/user-attachments/assets/0bcaeb24-4949-4a68-9c3d-a23adc78da3b)

![Image](https://github.com/user-attachments/assets/8380dc72-b0b9-49a0-ba2b-b7e62ac62ee3)

**Comment by SenpaiHunters** [comment] 2025-03-28 11:56
@solid-pixel make a new issue instead of commenting on old ones, also, while you're at it update to the newest dev build version. As, in `Version 🧪 1.3.0 (1459)` there is no issue on my end with the same mouse and settings.
