### ISSUE TITLE
🐛 Window Moves Back to Original Screen When Adjusting Size After Moving to Next Screen

### ISSUE THREAD

**Issue by quericy** [MrKai77/Loop#349] opened 2024-05-11 07:19 UTC
### Bug Description

When using the application to move a window from Screen 1 to the next screen (Screen 2) using a designated shortcut, and then attempting to adjust the window's size with another shortcut, the window unexpectedly moves back to Screen 1. The expected behavior is for the window to remain on Screen 2 and only have its size adjusted.

### Steps To Reproduce

1. Open any application window on Screen 1.
2. Use the shortcut to move the window to the Next Screen(Screen 2).
3. After the window appears on Screen 2, use the other shortcut to adjust the window's size.
4. The window moves back to Screen 1 instead of resizing on Screen 2

### Expected Behavior

After moving the window to Screen 2 and using the size adjustment shortcut, the window should resize on Screen 2 and remain there.

### Actual Behavior

The window moves back to Screen 1 when attempting to resize it after moving it to Screen 2. 

This occurs without any further interaction with the window on Screen 2. However, if the window on Screen 2 is manually clicked at least once before using the resize shortcut, the window stays on Screen 2 and resizes as expected.

### MacOS Version

Ventura 13.2.1

### Loop Version

Version 1.0.0-beta.15 (817)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment] 2024-05-11 17:22
Interesting, by any chance, does the mouse stay on the first screen? Loop currently resizes windows on the screen containing the mouse, but that will be fixed by #251.

**Comment by quericy** [comment] 2024-05-13 07:50
Yeah，the mouse stay on the Screen 1.

**Comment by MrKai77** [comment] 2024-05-13 22:20
Alright, I will close this as a duplicate of #251 :)
It is something I plan to fix before the next release, so stay tuned!

**Closed as not planned by MrKai77** 2024-05-13 22:20 UTC
Labels: Bug
