### ISSUE TITLE
🐞 Can't access settings once the menu bar icon is hidden

### ISSUE THREAD

**Issue by timpcmr** [MrKai77/Loop#345] opened 2024-04-30 19:56 UTC
### Bug Description

I made the mistake of hiding the menu bar icon through the option from Loop's settings. Now I can't access those even If I uninstall the app and erase all of it's preference and application state files

### Steps To Reproduce

1 [Go to settings] And toggle the "Hide menu bar icon"
2 [You can't open the settings anymore] I feel quite doomed

### Expected Behavior

I hope that clicking on the icon of Loop in SpotLight or app launcher would make the settings panel appear but it's not the case.

### Actual Behavior

The settings doesn't appear when you launch again the app

### MacOS Version

[Sonoma 14.4.1]

### Loop Version

[ 1.0.0 Beta 15

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment] 2024-05-01 01:45
That's weird, I just tried hiding the menubar icon and then tried opening Loop with Spotlight/Finder and the settings window opened fine.

Are you 100% sure that it didn't work? Because there's a possibility that Loop's window didn't open at the very front, and might have been hidden behind other windows.

**Comment by timpcmr** [comment] 2024-05-01 21:30
https://github.com/MrKai77/Loop/assets/98650963/0db4b56a-9230-497b-aabf-5a0d9cb41a05

Yes I'm affirmative... Do you know how could I clean all the preference files used by the app ? I tried to delete/modify the plist file in Preferences, installed from the zip instead of using HomeBrew etc...

Kind of a weird behaviour

**Comment by MrKai77** [comment] 2024-05-01 23:46
Interesting...

> Do you know how could I clean all the preference files used by the app? I tried to delete/modify the plist file in Preferences, installed from the zip instead of using HomeBrew etc...

Yes, that should delete all of Loop's settings. So I'm guessing that it's not the settings that are causing the problem.

And you stated previously that opening the app from Finder doesn't open the settings window either, so that's a really odd bug :(

---

I just tried using another method to detect when the settings window should re-open, so please try this build :)
[Loop.zip](https://github.com/MrKai77/Loop/files/15182253/Loop.zip)

**Comment by MrKai77** [comment] 2024-05-01 23:46
(Sorry, I didn't mean to close the issue)

**Comment by timpcmr** [comment] 2024-05-02 15:04
It still does not work... 
It just asked me to reset the authorisations that I removed for Loop.
Maybe my machine configuration is to blame... If I'm the only one concerned maybe don't bother too much with this !

**Comment by MrKai77** [comment] 2024-05-11 19:57
Alright.. since I don't have any other reports for this, I will mark it as low-priority.
However, to anyone else reading this, if you are encountering this same issue, please leave a comment below :)

**Comment by 1123123w** [comment] 2024-05-28 03:27
I have same issue, it work just fine when the menu bar icon is off at first, but after I turn off the preview ,it doesn't work. while trying this I try reopen the preview.it work again, but I can turn it off and work fine now.

**Comment by 1123123w** [comment] 2024-05-28 03:31
sry,i reporting an issue that doesn't about the topic.

**Comment by rizassh** [comment] 2024-06-09 09:27
Hello, I have the same issue. I'm not able to open the settings after hiding the menu bar icon.

**Comment by MrKai77** [comment] 2024-06-18 04:59
Can you please confirm that you can still reproduce this issue in the newest release (1.0.0)?

**Comment by SenpaiHunters** [comment] 2024-06-30 15:22
Hello, @Shazbg  , @1123123w , @timpcmr. Can you three go to https://github.com/MrKai77/Loop/releases/download/prerelease/Loop.zip the pre-release section, and check if that version of loop still has your issue. I tested it and cannot replicate it.

**Comment by MrKai77** [comment] 2024-07-03 02:38
Closing due to inactivity.

**Closed as not planned by MrKai77** 2024-07-03 02:38 UTC
Labels: Bug
