### ISSUE TITLE
✨Trigger and mouse gesture

### ISSUE THREAD

**Issue by hwlcsx** [MrKai77/Loop#204] opened 2024-02-04 08:11 UTC
### Feature Request Description

Press and hold trigger key , then on mouse gesture left / right  maybe good

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment] 2024-02-04 08:14
Thanks for your feature request! Would you be able to further explain how this would work? Also specify what you mean by "mouse gesture" (since that can mean many different things)?

**Comment by MrKai77** [comment] 2024-02-13 00:36
I will assume that this is a duplicate of #138 and will close this issue. Let me know if I was wrong :)

**Closed as completed by MrKai77** 2024-02-13 00:36 UTC
Labels: Feature
